### ISSUE TITLE
Request for list view with more info

### ISSUE THREAD

**Issue by realcopacetic** [realcopacetic/skin.copacetic#111]
https://forum.kodi.tv/showthread.php?tid=373114&pid=3183413#pid3183413

**Comment by nasawyer7** [comment]
Hi, I've been running into the same issue mentioned in the original comment.

"1. No matter how many times I tried to switch the view in certain video addons - to either BILLBORD or SHOWCASE or STRIP or GRID - after exiting and getting back the view is always set as a LIST.
No problem with view setups for local medias."

I was hoping there could be a way to default a view to a strip or another view, because when using addons it will never put the default view to a strip, it will always be list. 

I was also wondering if it would be possible to display imdb/trakt rating on the list info aswell? That's the one thing I typically google, if that is ever added, this skin would be a perfect skin imo. It might be easy to add this functionality if you use tmdb (the movie database) addon to pull that rating. 

I love this skin btw! Thank you for developing it, definitely the prettiest kodi skin I've ever seen.

**Comment by realcopacetic** [comment]
hi @nasawyer7  - are we talking about Fen/Fen Light? I don't use them, but I tried installing them as someone else mentioned they were having the issue about the views not being set and I wanted to know why it was happening. Looking at Fen Light, reason seems to be that the addon is seting the view back to list. I don't know why it wants to do this, but if you remove this line, it no longer happen and will remember the views you set for each media type (movies, tv shows etc) same as it does for library content:

Addons > plugin.video.fenlight > resources > lib > modules > kodi_utils.py
LIne 112
execute_builtin('Container.SetViewMode(%s)' % view_id)

**Comment by realcopacetic** [comment]
I've opened an issue to see if the developer will respond: https://github.com/Tikipeter/tikipeter.github.io/issues/47

**Comment by realcopacetic** [comment]
Regarding imdb/trakt ratings, there's an option in skin settings to use MovieDBHelper as the source for infoscreens instead of local library. If it's easy to do I'll add another option to use it to add those flags

**Comment by nasawyer7** [comment]
Thanks for responding so quickly and thourghouly! I'll probably just waite for the developer to fix this issue, since I run kodi on the android tv app, and it is difficult to edit files like that on a tv. (no free ssh, adb sucks for that). 

But yes, I was talking about fen light.

I'm not able to find where the option is to use imdb trakt ratings from tmdbhelper in settings, could you lmk what the path is for that? I look forward to this addition if its easy for yah

And if anyone else has this issue, here is a version of the funlight with that file removed, just put it on a  usb and install from usb:

[plugin.video.fenlight.zip](https://github.com/user-attachments/files/15995913/plugin.video.fenlight.zip)

**Comment by realcopacetic** [comment]
Hi @nasawyer7 just an update from the developer of Fenlight which you can see here. 

> The code you commented out is to set the view for the container, based on the user's preference in Tools->Set Views.
> 
> Unfortunately, video addons have always had to handle setting views in their addons (if they want to do that).
> 
> When the user sets their view in the addon, xbmcgui.Window(xbmcgui.getCurrentWindowId()).getFocusId() is used to get the view's ID, and xbmc.getInfoLabel('Container.Viewmode')) is used to get the view name.

Does this help? I've just tested and it works well, you can set the view for each content type:

Go to Context Menu > Options... > Open Tools > Set Views

**Comment by realcopacetic** [comment]
> the option is to use imdb trakt ratings from tmdbhelper in settings, could you lmk what the path is for that? I look forward to this addition if its easy for yah

So currently this isn't possible. The existing option is to use tmdbhelper as the source for widgets on the infoscreen (Settings > Copacetic > Customsiations > Info Screens). What I meant was, as I already have it set up to change functionality if tmdbhelper is present on the user's system, I should be able to create an additional setting that lets you display additional ratings if tmdbhelper is active on your system.

I just have to figure out how these user ratings work. Are you using them in another skin? I see there's talk of having APIs for other platforms such as OMDB and Trakt etc, so not sure how straightforward this is, or if it's all set up in TMDB Helper and then I just need to visualise it in my skin

**Comment by nasawyer7** [comment]
Sorry for the late response, I've been very busy. But yes, the artic zephyr reloaded skin uses tmdb to bring up ratings. 

When you said you go to Go to Context Menu > Options... > Open Tools > Set Views, Where is that in kodi settings? I was unable to find that. 

And thanks again for the help to this point! It is pretty much already fixed if you just change that one line in fen light

**Comment by realcopacetic** [comment]
hi no worries @nasawyer7 - it's a Fen Light setting, so when you open Fen Light, there are two ways to get to Toools. It's at the bottom of the main list that has Movies, TV Shows, People, Search, Discover, etc...).

Alternatively when you're on an item like a movie or a tv show inside Fen Light, hold down OK, or press C and the context menu will appear for that item and there will be a link to Tools there as well.

Once in tools, go to Set Views and follow the instructions from there. TO change the views for Movies, go to Movies, Choose the view you want to use, then press OK, and it will save it. You can set different views for each different content type and menus as well.

Flags I'll look into when I get some time
