### ISSUE TITLE
truncated grid when browsing movies

### ISSUE THREAD

**Issue by pasnox** [realcopacetic/skin.copacetic#127]
the grid view could be better if we could completely see entirely the two rows.
Currently we can only see one and a half, constantly needed to scroll to see next.
![IMG20240327143418.jpg](https://github.com/realcopacetic/skin.copacetic/assets/858201/c7591068-bcfc-4453-ac21-85541d159b66)

**Comment by realcopacetic** [comment]
This is by design to ensure it is clear there is more content. If you wish to see two rows, I would recommend switching to fanart view. 

I was not planning to amend the views further in the foreseeable future, but perhaps you could see if there is any further interest in such a chance in the forum here: https://forum.kodi.tv/forumdisplay.php?fid=320
