### ISSUE TITLE
Resource.fonts.copacetic

### ISSUE THREAD

**Issue by mmc45** [realcopacetic/skin.copacetic#19]
Hi, 

I receive the error 

“The dependency on resource.fonts.copacetic 1.0.3 could not be satisfied”

when attempting to install your skin on Kodi Nexus. I’ve tried installing via the Kodi repository, and also directly from the .zip you’ve provided on the Kodi forum. 

I’m using a brand new clean install of Nexus on Windows 10. I’ve also tried installing the Copacetic Extra Fonts add on.

Many thanks,
Mark 

I should add that all other skins install correctly via Kodi repo, isolating the issue to Copacetic.

**Comment by realcopacetic** [comment]
@mmc45 yes this is an issue with the dependencies I pushed to the official Kodi repo. I will shortly push an update to the Kodi repo to change this dependency back to version 1.0.2. In the meantime, you can either manually change the number to 1.0.2 in your Kodi user folder if you go to /addons/skin.copacetic/addons.xml.

Alternatively, you can update resource.fonts.copacetic to 1.0.3 from my repo, which you can install by 

1. adding a new source in file manager --> https://realcopacetic.github.io/
2. Now if you go to settings > system > Add-ons and enable Unknown sources.
3. From the same screen choose 'Any repositories' under 'Update official addons from' - as this will allow Kodi to pull v 1.0.3 from my repo instead of needing to wait for the official kodi repo to be updated.
4. Going to addons > install from zip > then installing my repo.

I understand you may not want to do all that so I'll endeavour to push out an update asap to the officail kodi repo. It's taking a little longer than anticipated because there are some new automated checks that addon updates need to pass and the test run I did flagged up a few other small issues I need to fix before the update can be accepted. Hopefully it should be good before the end of the week.

Thanks for your patience.

**Comment by mmc45** [comment]
Thank you so much for your reply, I am really grateful! I’ll revert back to 1.0.2 until a fix is sorted. 

I wanted to congratulate you on such a fantastic skin - the screenshots blew me away. I appreciate the work you’ve clearly put into this.

**Comment by realcopacetic** [comment]
Hi @mmc45 thanks for the kind words. Just to confirm, the official repo has now been updated so this issue should be fully resolved. Thanks
