### ISSUE TITLE
[Feature request] Add Radios

### ISSUE THREAD

**Issue by freijon** [realcopacetic/skin.copacetic#22]
I really like this skin but it's unable to show Radios which is a killer for me.

Can this be added? Radios have a logo and would work well with the skin IMO

**Comment by realcopacetic** [comment]
Hi, do you mean [Add-on:Radio](https://kodi.wiki/view/Add-on:Radio) from the official repo?

I just tested and it's working for me. Once you install it, you need to add a shortcut to Radio on one of your menus (Main, Shutdown) or you can set up a widget. Otherwise the only way to open it is by going into your add-ons and going into the info on Radio then scrolling on the main menu to 'open'.

I have only tested it briefly on Nexus 20.2 but the radio stations I searched for would play and the music player widget also seems to work. Trying to play some radio stations would lead Kodi to crash, but I also observed this on Confluence, so without digging into it, I think it's an issue outside of this skin.

What I did notice is that:
a) Only the list view is working for this addon for some reason
b) Only the Radio addon artwork shows up, not that of the individual stations. 

So I'll look into getting those fixed. But please let me know if you are having some other issue that I've not managed to replicate.

**Comment by starman2908** [comment]
Hiya, great skin, I also noticed video add ons have list view only in main menus... Are you getting this too? (I. E. TMDB Helper).

**Comment by realcopacetic** [comment]
> Hiya, great skin, I also noticed video add ons have list view only in main menus... Are you getting this too? (I. E. TMDB Helper).

I'll check this, I thought I had set up views to work fully for video add-ons, but maybe there's a bug. I'll check this and report back, but certainly the views should work for video add-ons as long as the views are enabled for Videos and Music in the skin settings.

**Comment by freijon** [comment]
Sorry, I should have been more specific. I don't mean Radio Addons, but PVR Radio. Everything with PVR seems to be unimplemented.

**Comment by realcopacetic** [comment]
Oh yes, PVR is on the roadmap but I haven't got to it yet

**Comment by realcopacetic** [comment]
@starman2908 I just tested on TheMovieDB Helper and all views work for me when the container has actual content e.g. when I'm browsing movies. This is me browsing to In Theatres under Movies for example: 
![Screenshot 2023-07-27 at 23 05 57](https://github.com/realcopacetic/skin.copacetic/assets/14795443/4209d040-07bc-4ee9-9f6a-5fa1fd6438fd)

Where it is limited to List View is when navigating through categories, the reason being that in these parts there is no content type set by the plugin. Typically the approach is to fallback on icons e.g. this is what you see in TMDB Helper in Estuary.

![Screenshot 2023-07-27 at 23 09 05](https://github.com/realcopacetic/skin.copacetic/assets/14795443/33d3385a-7092-4745-ae6e-fdd33d02021e)

I iprefered instead to emphasise the background slideshow, although this does need to be enabled in Settings under 'Copacetic' > General > Enable background slideshows. Then you see it like this:

![Screenshot 2023-07-27 at 23 12 30](https://github.com/realcopacetic/skin.copacetic/assets/14795443/8165dedc-de21-4804-9d0e-a3b8397d2f80)

Would you prefer to have the listview with thumbnail icons insteada of background fanart when going through the categories?

**Comment by starman2908** [comment]
Ah yes, views work perfectly in containers for me too, and yeah that is the same result for me on list view in the categories. As a personal preference it would be great to see an icon,/grid,/square option, if anything because some of the lists can be quite long to scroll through. Also, really appreciate the work you guys do as developers and think it must have taken jurial ages to curate and create the icons for all the lists. It all comes down to time/effort as to how difficult it would be to implement and also to preserve the simplicity of the skin. 

Not withstanding it's only a personal preference, I'm happy with the list for category views as the container views are simply stunning when browsing, so kudos on the great work. Been using your skin for a good while now and have loved seeing it going from strength to strength, also congrats on having it on the official repo now! Well deserved! And thanks for all the effort and time you put in.

**Comment by realcopacetic** [comment]
Thanks @starman2908 , appreciate the feedback. It shouldn't be too hard to add list view with thumbnails and grid view as options for browsing lists with icons. I probably won't add the other views because the larger artwork space generally ends up making small icons look quite blurry

**Comment by starman2908** [comment]
Ah that would be cool. Yeah, totally agree other views would distort icon images too much, especially on larger displays. Look forward to your updates. 

Also Wow! had no idea about the background sideshows... Looks great in my library playlists... Is it pulling content that already exists from my video library or fetching it from the highlighted addon container?

EDIT **  Never mind, Just figured out its my library content, there's content within container lists that I deffo don't have 😂

**Comment by realcopacetic** [comment]
Yes just from your library. I'm not sure if there's a way to pull artwork that has been cached from plugins

**Comment by starman2908** [comment]
Nah I wouldn't have thought so, even if there was a way to setup the background to pull art from the list container I doubt it would be worth the effort since the list is just a glance before clicking into the container anyways.. I can't even imagine the load times would be worth it.

I think the background is pretty cool as is and works well with library content. I just got a shock how you managed to pull from a container, but then realised it was a coincidence that like the first ten backgrounds from my library matched most of the first container I clicked into from the list on TMDB helper. 🤦

**Comment by realcopacetic** [comment]
**Added to 1.1.6** 
- Ability to switch between List (Background), List (Thumbnails) and Grid views for plugins when there is no container content type set (e.g. when browsing menus in TheMovieDB Helper)
- Removed ability to disable slideshows in order to simplify logic of light theme

_This will be live in my repo shortly and in the official Kodi repo after a period of additional testing._

**Comment by realcopacetic** [comment]
@freijon I've closed this issue for now as I already have a separate issue for adding PVR support, thanks
