### ISSUE TITLE
Music OSD disappears - Black screen

### ISSUE THREAD

**Issue by freijon** [realcopacetic/skin.copacetic#30]
I have two Android TV's and use the skin on both. But on one device the Music OSD disappears after a few seconds and fades to a black screen. The strange thing is, this doesn't happen on the other device.

I checked all settings and didn't find any setting that would change this behavior. What am I missing here? I'd like the Music OSD to be always visible.

**Comment by realcopacetic** [comment]
Can you confirm if you are using the same version of the skin on both devices?

Do you mean on the music visualisation screen? Music OSD is set to autohide after a brief period by default

**Comment by freijon** [comment]
I installed it on both devices yesterday, so they should be the same version.

I mean the screen where the album cover is shown with the progressbar at the bottom.

**Comment by realcopacetic** [comment]
So this is standard Kodi behaviour. It is designed to work as a toggle, so people can choose if they want the osd and album fanart to show or to hide the info and let a background visualisation take the screen instead.

Press info to toggle the album art and song details to stay visible. Alternatively if you prefer, you can install a visualisation addon and it will show instead of a black screen. 

I'll close this issue for now, but pleaes reopen if this does not address your issue, thanks
