### ISSUE TITLE
[Feature Request] - LibreElec settings menu

### ISSUE THREAD

**Issue by TheOne988** [realcopacetic/skin.copacetic#54]
Hi @realcopacetic,

is it possible for you to add the "LibreElec settings menu" to be visible in the main settings menu. At the moment you cannot open this menu you need to change skin in order to be able to access it. 

![screenshot00000](https://github.com/realcopacetic/skin.copacetic/assets/36518440/0f89056c-cf3e-44da-adc4-c3ce49ca9f24)
![screenshot00001](https://github.com/realcopacetic/skin.copacetic/assets/36518440/2971b4c0-e7bf-4b7d-b7f9-d2cd7a58522a)

**Comment by realcopacetic** [comment]
Hi @TheOne988, it turns out this is a shortcut to run an addon called service.libreelec.settings. 

It will be quite hard to integrate this into the settings screen as I have it, where each time you press up/down on the main menu at the top, it's actually opening a different window. But they're all styled the same so it feels like one continuous menu with the content just changing on the right as you scroll through. 

I couldn't get Addons to work in this way, which is why I don't have a link to the Addon browser here like Estuary does.

For that reason, I think the best way for you to have easy access to LibreElec (and Addons) would be to add to the shutdown menu. 

I can hardcode it with a visibility condition, but you might be able to add it already by creating a shortcut to point at the relevant addon (service.libreelec.settings)

**Comment by realcopacetic** [comment]
Like this.

<img width="1440" alt="Screenshot 2023-08-07 at 22 22 20" src="https://github.com/realcopacetic/skin.copacetic/assets/14795443/2d6e5b80-047b-4a09-86f2-87b9f322d8a2">

**Comment by TheOne988** [comment]
Hi @realcopacetic,

thanks for the info. There is no need to hard code it and to cause any future unplanned problems.
I will add it as you recommend to the shutdown menu.

Cheers
