### ISSUE TITLE
Multiart not working on billboard home widgets

### ISSUE THREAD

**Issue by realcopacetic** [realcopacetic/skin.copacetic#60]

**Comment by randomragenet** [comment]
It doesn't work with the info screen on grid mode, either.
Expected behavior: Grid screen -> go to Info screen with multiple fanart -> while on info screen, slide show plays in background (not too quickly though that would be distracting)

This might be considered a feature request: use multiple fan art for info screen background

**Comment by realcopacetic** [comment]
Thanks for the feedback, that's a great idea that I don't know why I didn't think of before! I will add this soon

**Comment by realcopacetic** [comment]
Fixed in 1.1.16.

@razordullwit - I have also added the mutliart slideshow to the infoscreen so it should scroll through all available fanarts for a given item now. 

1.1.16 I'll push shortly to my repo and then soon to Kodi's official repository
