### ISSUE TITLE
Option to customize animations duration

### ISSUE THREAD

**Issue by lwouis** [realcopacetic/skin.copacetic#73]
Hi,

First of all, thank you very much for this skin. It is incredibly well-thought and elegant. Thank you for sharing your work with all of us.

When going from one place to the other in Kodi, sometimes I know exactly where I want to go, but I'm slowed down by waiting for fade-in animations. Do you think it would be possible to add an option to customize the duration, or a toggle to simply disable animations?

Thank you 🙇

**Comment by realcopacetic** [comment]
The fade times are all pretty short, do you mean what happens when sometimes you open, for example, movies and it takes 3-4 servings to load in? 

If that's what you mean you'll notice subscribe loads are mush faster and reflective of the animation time. The delay on first load is due to the code being loaded in. Because my views are built slightly 'manually', ie they don't really on Kodi's built in containers, there's basically a lot more code to load. If that's the case you can mitigate the load time by dialing any views or extras that you don't use in skin settings

**Comment by lwouis** [comment]
Hi @realcopacetic,

Thank you for your response!

I'm not talking about some one-time-the-first-time delay. I'm saying that there are fade-in animations in most places. They look very nice and refined. However, I would personally prefer a snappier experience. That is, a preference to select how long all these animations last for. I would set that to 0 and have instant transitions.

Here are 2 videos I recorded to showcase some of those fade-in animations I'd like to disable through a preference:

https://youtu.be/hgpk6Gw3Rns
https://youtu.be/nO1hl0LCBxE

Thank you 🙇

**Comment by realcopacetic** [comment]
I see what you mean. Unfortunately it's not so straightforward because it's not just about an option to disable the animations but also about disabling a number of expressions and hidden windows that are used to create a time period for a transition effect between different states within the same window, e.g. when you go from tv shows > seasons > episodes, there's a transition on each level even though you stay within the movies window, so the window load/unload animations aren't even used for this effect.

Next time I have some time I'll see how straightforward it is to give an option to disable this

**Comment by realcopacetic** [comment]
Hi @lwouis

I had a go at having an option to shorten animation times, unfortunately it starts causing things to break and certain things not to appear properly or at all, the reason being that a lot of the animation times are tied in with hidden windows that need to have hardcoded transition times. So I don't think I'll be able to do much here. One thing you might be able to try though is in the addon.xml, for skin.copacetic, there is a value called effectslowdown="0.8". This is a multiplier that i think is applied to all timings universally. Currently it's at 0.8. 1.0 is default, so if you put this lower it should make things faster. E.g. 0.4 should be half of the speed of the current values. I haven't tested this so I don't know how well it works or if it will cause some things to break.

**Comment by lwouis** [comment]
Hi @realcopacetic,

Thanks a lot for your help!

I tried to change `effectslowdown` to `0.0` but it didn't seem to work. I tried with `0.1`, and that seems to work. Animations are pretty fast now. The sound effect is unchanged, and the experience feels good. I haven't encountered issues with it for the moment.

If it's possible, it could be a quick win to expose a preference to the user, in the UI, to set this variable.

In any case, my issue is gone, so please feel free to close this ticket 👍 

Thank you for your support, and thank you again for making this beautiful skin!

**Comment by realcopacetic** [comment]
I'm not sure if that's possible but will look into it. One thing to keep in
mind is that if you update the skin from the repo, it will revert to the
default value

**Comment by llbstr** [comment]
Hey, I was also looking to ask for a more snappy interface with lowering animations and I found this post.
I tried to edit the "effectslowdown" value but my device is not rooted so I can't make modifications on the device, and when edit the file on my computer, then zip the source code here with the edit, I can't update the skin addon (dependency install issue according to log). Anyway, great skin, it looks splendid so I'll keep using it :)

**Comment by realcopacetic** [comment]
hi @llbstr / @lwouis - I've been working on this in the background. One question for you both. Are there any areas you think shouldn't be sped up?

I ask because for me, some of the views like Strip and Showcase become pretty difficult to use if they get too fast. So I was thinking of keeping the main transition speed on lists the same, but then reducing the animation times for window loads, dialog popups etc.

**Comment by llbstr** [comment]
Hey, thanks for the addition! I was just trying the new transition setting, I like it the most when I'm in the the settings/addons/anything related to settings, and I also think that initial speed would be best for browsing movies/shows/music/lists.

**Comment by lwouis** [comment]
Hi @realcopacetic,

Thank you for your message.

I'm using the Strip and List views. Both feel very good to me with `effectslowdown` at `0.1`. Here's a [video of what the experience looks like on my TV](https://youtu.be/gB-VGYi6BeI).

When using software, I like when it's responsive. I've removed the default Android TV launcher, and also removed lots of things which would take compute in the background. My TV is now responsive and I never see micro freezes when navigating in Kodi, as I used to experience often in the past.

With the fast animations in the Copacetic skin, I'm enjoying a very sophisticated and efficient experience, when viewing movies or TV shows at night.

Thank you again for your work on this skin. It is quite a work of art.

Thank you 🙇

**Comment by realcopacetic** [comment]
hi @lwouis @llbstr - I've made some new additions in 2.5.0 (Omega) / 1.5.0 (Nexus), which will be available shortly.

As context, the current animations are calibrated to a base time of 360ms. With the 0.7 `effectslowdown`, 

I've added two new options under Settings > Copacetic > General > Look and Feel.

1) The first is called "Speed up animations and window transitions [BETA]". This sets the base time for animations from 360ms to 100ms (0.7 `effectslowdown` brings this to 70ms). It also removes a lot of the delays in things like text appearing after you scroll to an item in your list. Currently the scrollspeed on Showcase and Strip is still the default timing because there's not an easy way to speed this up without making a hack where a script changes the value of the settings in the XML. But it should still much faster as there's no delay waiting for the text to appear.

One thing to note on this. Clearlogo cropper *should* just about be able to keep up with this, but if it feels glitchy you'll need to disable this.

2) Second option becomes visible when first option is turned on. It's right underneath and is 'Disable all viewtype scroll animations' - this sets the scroll time for views to zero, so there's no animation, the content immediately shifts place. Clearlogo cropper doesn' work with this, it's too fast to be displayed, so the standard clearlogo is displayed instead, although the clearlogo cropper is still running in the background, so if you don't want that, then you can turn it off in the settings.

**Comment by realcopacetic** [comment]
Marking this as closed in case either of you wish to reopen with further feedback/requests. Thanks
