### ISSUE TITLE
Inconsistency in the shutdown menu.

### ISSUE THREAD

**Issue by berettavexee** [realcopacetic/skin.copacetic#89]
Capocetic version 1.1.16 from LibreElec official depot. Fresh libreElec install with the base package, copacetic and two video extension (ARTE+7 and France.tv)

When I go to the shutdown menu, the menu displayed does not correspond to the one in the configuration (see screenshots).

The extension/add-on entry in the menu generates a sound but does not open the extensions/add-on menu.
The entry to quit kodi does not appear.

If repeated press on the extension entry, kodi may crash and restart.

Kodi.log
`023-11-10 22:45:14.106 T:4266     info <general>:   skin loaded...
2023-11-10 22:45:14.106 T:4266     info <general>: Loading skin file: Home.xml, load type: KEEP_IN_MEMORY
2023-11-10 22:45:19.742 T:4266     info <general>: Loading skin file: DialogButtonMenu.xml, load type: KEEP_IN_MEMORY
2023-11-10 22:45:22.342 T:4266     info <general>: Activate of window '10040' refused because there are active modal dialogs
2023-11-10 22:47:29.940 T:4266     info <general>: Loading skin file: Settings.xml, load type: KEEP_IN_MEMORY
2023-11-10 22:47:29.973 T:4266     info <general>: Loading skin file: SkinSettings.xml, load type: LOAD_EVERY_TIME
2023-11-10 22:47:38.339 T:4266     info <general>: Loading skin file: /storage/.kodi/addons/skin.copacetic/16x9/script-skinshortcuts.xml, load type: LOAD_ON_GUI_INIT
2023-11-10 22:47:38.507 T:4837    error <general>: EXCEPTION: Non-Existent Control 309
2023-11-10 22:47:38.539 T:4266     info <general>: Loading skin file: DialogConfirm.xml, load type: KEEP_IN_MEMORY
2023-11-10 22:47:38.546 T:4839    error <general>: GetDirectory - Error getting /storage/.kodi/userdata/library/video
2023-11-10 22:47:38.549 T:4839    error <general>: GetDirectory - Error getting /storage/.kodi/userdata/library/music
2023-11-10 22:48:05.880 T:4266     info <general>: Attempting to default to: 
2023-11-10 22:48:05.880 T:4266     info <general>: Loading skin file: FileManager.xml, load type: KEEP_IN_MEMORY
2023-11-10 22:48:07.039 T:4266     info <general>: Loading skin file: SkinSettings.xml, load type: LOAD_EVERY_TIME
2023-11-10 22:48:07.680 T:4266     info <general>: Loading skin file: SettingsCategory.xml, load type: KEEP_IN_MEMORY
2023-11-10 22:48:09.930 T:4266     info <general>: Loading skin file: DialogSelect.xml, load type: KEEP_IN_MEMORY` 

Screenshot
https://imgur.com/a/E5vuKZQ

I'm just starting out with Kodi/Libreelec. I don't know if there are any other logs available that could help you.

**Comment by realcopacetic** [comment]
Hi shutdown menu has 4 hardcoded items at the start. The reason they're hardcoded is because they have conditional visibilities that are not possible for users to add via skinshortcuts themselves. The hardcoded items are:

Home - available when the home window isn't visible
Light/Night - quick setting theme switcher 
Settings - hardcoded to ensure people don't lose access to settings if they would accidentally remove a shortcut
LibreElec - A settings screen exclusive to the libreElec platform and only visible when you're on that platform. 

I see you added two yourself, Extensions and Quitter, so what you should see if you access from the home screen, for edxample is:

Nuit / Parametres / LibreELEC / Extensions / Quitter

The issue seems to be why Quitter isn't showing up. Could you share the contents of the file found in addons/skin.copacetic/16x9/script-skinshortcuts-includes.xml please?

**Comment by realcopacetic** [comment]
I've also fixed that error Non-Existent Control 309 in 1.1.17 but I don't think that would have any impact on this

**Comment by berettavexee** [comment]
> I see you added two yourself, Extensions and Quitter, so what you should see if you access from the home screen, for edxample is:

I didn't modified the shutdown menu. I've even reset all the menus several times using the "reset all menus" entry, which resets the home menu and the shutdown menu. And via the reset icon in the shutdown menu configuration screen. I always get these two entries for the shutdown menu.

addons/skin.copacetic/16x9/script-skinshortcuts-includes.xml : https://pastebin.com/46g7JpgU

I tested the video extensions using the tv show menu. Both extensions work perfectly.

Thank you for your efforts and your prompt reply

**Comment by realcopacetic** [comment]
I believe it's not showing because LibreELEC does not support exiting kodi. 

https://forum.kodi.tv/showthread.php?tid=321985#:~:text=LibreELEC%20is%20it's%20own%20Linux,only%20options%20you%20will%20have.

So you should be able to add a shutdown menu item but not exit

> LibreELEC is it's own Linux distro which doesn't provide any command line shell if you "exit" Kodi. So "Shutdown", "Reboot", "Shutdown timer" and "Suspend" (if it is capable of) are the only options you will have.

**Comment by realcopacetic** [comment]
Regarding Extensions not opening, I will need to investigate further. This was an issue for some people before, I think something to do with Linux. I'll need to look into it

**Comment by berettavexee** [comment]
I carried out a few complementary tests:
- If I delete all the entries in the shutdown menu, and then reset the menus, both entries reappear in the shutdown menu.
- If I add an entry on the home menu with ActiveWindows(Videos,Addons,return) action, the video extensions window opens and works correctly.
- Exactly the same entry in the shutdown menu doesn't work.
- If I add a second entry on the shutdown menu with ActiveWindows(Videos,Addons,return) action, the video extensions window don't open. I have moved the entry location in the menu with no effect
- If I modify the extension entry in the shutdown menu to point to another action such as pointing to the video or music library, the interface generates a sound but doesn't open a window. 
- Modifing the quit() entry to shutdown() shutdown LibreElec as espected

P.S. By the way, I've completed the French translation in Weblate and it should be 99% complete. Thanks again for your efforts.

**Comment by realcopacetic** [comment]
Hi, I think the issue with this may have been that the file at skin.copacetic/shortcuts/Overrides.xml has a capital 'O', which Linux doesn't like and is causing it to ignore the file and a line about ensuring all modals are closed when any shortcut is pressed iin the shutdown menu. This is fixed in the latest version in my repository although not yet in the official repo, but I will submit an update there shortly. 

If you are happy to install updates from my repo directly, you can test if this fixes the problems by following the instructions here: https://forum.kodi.tv/showthread.php?tid=373114&pid=3152676#pid3152676

Thanks for doing the French translation, really appreciate the support.
