### ISSUE TITLE
inter noto sans font does not fully support chinese

### ISSUE THREAD

**Issue by ezatgz** [realcopacetic/skin.copacetic#97]
it only shows part of chinese characters correctlly, some characters just shows as horizon lines...kindly pls help on this issue

**Comment by ezatgz** [comment]
it fixed my problem by replacing font ttf file with MiSan font ttf file.
link for MiSan font https://hyperos.mi.com/font/download

**Comment by realcopacetic** [comment]
Hi @ezatgz , the current font you mentioned Inter + Noto Sans KR was a request for Korean support. The reason I made a font like this was because I wanted to ensure Inter remains the font for any Latin characters - for things in the skin that haven't been translated from English, or items in your library with Latin characters.

Noto has support for full CJK characters but split across different fonts. There's Simplified Chinese, Traditional Chinese and Traditional Chinese HK. 

[https://github.com/notofonts/noto-cjk/tree/main/Sans/OTF](https://github.com/notofonts/noto-cjk/tree/main/Sans/OTF)

I assume for a modern use case like this, Simplified Chinese would be sufficient. Please confirm then I can add it to my addon [resource.fonts.copacetic](https://github.com/realcopacetic/resource.fonts.copacetic/tree/master).

**Comment by ezatgz** [comment]
Hi @realcopacetic , I did a test to replace .ttf files of native Copacetic Extra Fonts addon with NotoSansCJKsc font files, the result is great, not only Simplify Chinese but also Traditional Chinese, Japanese, Korea, English all displays properly.

Here's detail of the test.

**Test Environment:** 
Maven-build Kodi 20.2 on Sony Android TV

**Test Step**
1. Download SC/SC/Japanese/Korea Kodi language addon

2. Download below six font files from https://github.com/notofonts/noto-cjk/tree/main/Sans/OTF/SimplifiedChinese  to my laptop

- NotoSansCJKsc-Black.otf
- NotoSansCJKsc-Bold.otf
- NotoSansCJKsc-DemiLight.otf
- NotoSansCJKsc-Light.otf
- NotoSansCJKsc-Regular.otf
- NotoSansCJKsc-Thin.otf

3. Rename above six files
- Rename NotoSansCJKsc-Black.otf to Inter-NotoSansKR-Black.ttf
- Rename NotoSansCJKsc-Bold.otf to Inter-NotoSansKR-Bold.ttf
- Rename NotoSansCJKsc-DemiLight.otf to Inter-NotoSansKR-SemiBold.ttf
- Rename NotoSansCJKsc-Light.otf to Inter-NotoSansKR-Light.ttf
- Rename NotoSansCJKsc-Regular.otf to Inter-NotoSansKR-Regular.ttf
- Rename NotoSansCJKsc-Thin.otf to Inter-NotoSansKR-ExtraLight.ttf

4. Copy over files in step 3 to overwrite font files of Copacetic Extra Fonts addon and reboot Kodi

5. Set skin font to Inter + Noto Sans KR 
 
6. Switch Kodi interface Language between SC/TC/Japanese/Korea/English. the font works great with all languages without any issue.

**Comment by ezatgz** [comment]
actually medium font weight is most close to demi bold. i should use medium one but not the demilight.

**Comment by realcopacetic** [comment]
Fixed in **1.1.18**
